name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  # ------------------- UNIT -------------------
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run unit tests (no DB)
        run: pytest -q
        working-directory: tests/unit
        env:
          PYTHONPATH: ${{ github.workspace }}   # ✅ racine du repo
          SKIP_DB_INIT: "1"

  # ------------------- INTEGRATION -------------------
  integration:
    if: github.event_name == 'pull_request'   # ✅ PR/MR only
    needs: unit                                # (optionnel) attend que unit passe
    name: Integration Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: water
          POSTGRES_PASSWORD: water
          POSTGRES_DB: water
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U user -d watertracker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run integration tests
        run: pytest -q
        working-directory: tests/integration
        env:
         PYTHONPATH: ${{ github.workspace }}
         DATABASE_URL: postgres://water:water@localhost:5432/water