name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  # ------------------- UNIT -------------------
  unit:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run unit tests (no DB)
        run: pytest -q
        working-directory: tests/unit
        env:
          PYTHONPATH: .
          SKIP_DB_INIT: "1"   # ⬅️ empêche l'init DB pendant les unit tests

  # ---------------- INTEGRATION (PR only) ----------------
  integration:
    name: integration-tests (PR only)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: watertracker
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d watertracker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run integration tests (with DB)
        run: pytest -q
        working-directory: tests/integration
        env:
          PYTHONPATH: .
          DATABASE_URL: postgres://user:pass@localhost:5432/watertracker
          # PAS de SKIP_DB_INIT ici -> on veut init_db()

  # ------------------- UI (main only) -------------------
  ui:
    name: ui-tests (main only)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (selenium + chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux.gpg
          echo "deb [signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install -r requirements.txt
          pip install selenium webdriver-manager
      - name: Start app (Flask, no DB)
        run: python -m flask --app app run --host=0.0.0.0 --port=8000 & sleep 5
        env:
          FLASK_APP: app
          PYTHONPATH: .
          SKIP_DB_INIT: "1"   # ⬅️ pas d’init DB pour l’UI
      - name: Run UI tests
        run: pytest -q
        working-directory: tests/ui
        env:
          APP_URL: "http://localhost:8000"
          PYTHONPATH: .
