name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  # ------------------- UNIT -------------------
  unit:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run unit tests (no DB)
        run: pytest -q
        working-directory: tests/unit
        env:
          PYTHONPATH: .
          SKIP_DB_INIT: "1"   # ⬅️ empêche l'init DB pendant les unit tests
